# Generated by Django 4.2.7 on 2023-12-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommencer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-SHIRT', 'T-Shirt'), ('JACKET', 'Jacket'), ('SWEATSHIRT', 'Sweatshirt'), ('PANTS', 'Pants'), ('ACCESSORIES', 'Accessories')], default='T-SHIRT', max_length=12),
        ),
    ]
