# Generated by Django 4.2.7 on 2023-12-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommencer', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
