# Generated by Django 4.2.7 on 2024-01-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommencer', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
